Gemfile
app/controllers/home_controller.rb
config/routes.rb

The last PR created some rubocop errors, but I can't get mad, seeing as rubocop hadn't been added yet when you created your branch :-)

Fix some rubocop warnings

---

app/views/developments/index.html.haml

The index page was using a `<caption>` element for the page heading; it's been replaced with an `<h1>`.

(fix) correct heading hierarchy

---

Dockerfile

* This version of Rails requires SECRET_KEY_BASE set. We can just set it
to 'dummy' to allow it to run
* https://github.com/rails/rails/issues/32947

(Fix) Add SECRET_KEY_BASE in Dockerfile

---

config/environments/prod.rb

For DXW hosting, we want logs to go to STDOUT, without having to set this ENV variable.
Staging environment also loads this file, so changes apply there.

Set production logging to STDOUT

---

docker-entrypoint.sh
variables.tf

* Also ensures that `db:create` is not ran in production - this needs to
be ran manually at first launch

(Chore) Run docker-entrypoint.sh

---

app/assets/stylesheets/_utilities.scss

(fix) adds an underline to the logout link

---

Gemfile
Gemfile.lock
app/views/developments/_form.html.haml
app/views/developments/edit.html.haml
app/views/developments/new.html.haml
app/views/devise/sessions/new.html.haml
app/views/dwellings/_fields.html.haml
app/views/dwellings/edit.html.haml
app/views/dwellings/index.html.haml
config/initializers/simple_form.rb
config/locales/simple_form.en.yml
db/schema.rb
lib/simple_form/optional_labels.rb

This PR: 
- adds the `simple_form` gem
- uses it to build the 'dwellings' form
- applies GOV.UK styles via a custom wrapper
- follows GOV.UK patterns for error reporting (i.e. both inline and top-of-page summary)

add simple_form

---

app/helpers/page_title_helper.rb
app/views/developments/edit.html.haml
app/views/developments/index.html.haml
app/views/developments/new.html.haml
app/views/developments/show.html.haml
app/views/devise/sessions/new.html.haml
app/views/dwellings/edit.html.haml
app/views/dwellings/index.html.haml
config/locales/en.yml
spec/helpers/page_title_helper_spec.rb

this PR:
- adds a helper and spec for creating page titles
- uses the more specific fragment of the page title before the generic fragment (better for screen readers)

page titles are better for accessibility

---

app/controllers/developments_controller.rb
app/models/development.rb
app/views/developments/edit.html.haml
app/views/developments/new.html.haml
app/views/dwellings/edit.html.haml
app/views/dwellings/index.html.haml
app/views/partials/_error_block.html.haml
spec/features/creating_developments_spec.rb
spec/features/editing_developments_spec.rb

It's not entirely clear yet which of these fields are mandatory to be able to create a development. Do developments start getting logged/discussed before the have an application number/site address/proposal set? Probably not, but we want to keep it flexible until we find out.
However, if you create a development without an application number, then things start breaking, so let's require that.

Validate application number on development

---

app/views/developments/_form.html.haml
app/views/developments/edit.html.haml
app/views/developments/new.html.haml
config/initializers/simple_form.rb

This PR makes for a better experience when a user edits a proposal, because multi-line text is visible in the form field.

proposal field is now a textarea

---

app/models/dwelling.rb
app/views/partials/changelog_descriptions/_dwelling_update.html.haml
spec/features/editing_dwellings_spec.rb

Nothing novel here compared to previous two audit actions.

Audit updates to a dwelling when it's development is not draft

---

Gemfile

We want to be able to run `rake db:seed` on the staging environment, so we need access to the faker gem.

Add faker to all Rails environments

---

app/views/developments/show.html.haml

(fix) adds missing class to link

---

.rubocop.yml
db/seeds.rb

When running the seeds, the system requires would create an audit log for any dwellings added to a dwelling that isn't in a draft state. This would also error because we're not adding an audit_comment to these changes.
I've turned off auditing for these seeds.
I also added seed.rb to the rubocop ignore list, as it was complaining about the block being too large, which is OK in this case.

Turn off auditing on seeds

---

app/controllers/developments_controller.rb
spec/features/developer_completion_response_spec.rb

Because the developer response form does not require sign-in, we want to restrict it a bit more. This captures two sceanarios:
- The developer visits a response form URL after they have already filled everything in. They are shown the completion page, instead of being able to edit what they had previously filled in
- The developer somehow finds the URL for the repsonse form before the development is in a `completed` state. This is very unlikely, but I've made it a 404 anyway.

Limit access to developer reponse form

---

Gemfile
Gemfile.lock
app/models/development.rb
app/models/dwelling.rb
spec/features/creating_dwellings_spec.rb
spec/features/deleting_dwellings_spec.rb
spec/features/editing_developments_spec.rb
spec/features/editing_dwellings_spec.rb

We had two bugs with the audited gem, and I've opened PRs for both of them:
https://github.com/collectiveidea/audited/pull/522
https://github.com/collectiveidea/audited/pull/523
In the meantime, while we're waiting for them to hopefully be approved and merged, I have created my own fork with a branch that has both of those changes in.
This means that we no longer need the monkey pathes in the dwelling and development models. Also update the specs to reflect the new, fixed error messages.

Use fork of Audited gem

---

app/views/partials/_changelog.haml

shows a better blank state for the changelog

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_table-scrollable.scss
app/assets/stylesheets/components/_width-container.scss
app/views/developments/complete_confirmation.html.haml
app/views/dwellings/index.html.haml

- if the developer response is submitted, show them in the dwellings table
- overrides the GOV.UK container max width and applies an elastic width for optimal display
- if the screen width gets too narrow to contain the table, it becomes horizontally scrollable
- removes the 'add a dwelling' button if a developer response exists
**without developer response:**
**with developer response:**

renders the developer responses for dwellings

---

app/assets/stylesheets/components/_subnavigation.scss
app/views/partials/_subnavigation.haml

(fix) removes hardcoded active nav highlighting

---

Gemfile
Gemfile.lock

I was using my own personal git url, rather than the public HTTPS url, which was causing problems with deploys.

Use HTTPS for audited gem git reference

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_development-search.scss
app/controllers/developments_controller.rb
app/models/development.rb
app/views/developments/_search.haml
app/views/developments/index.html.haml
spec/features/searching_developments_spec.rb

Uses PGSearch to allow searching the following fields:
- a development's application number
- a development's proposal
- a development's site address
- all of the development's dwellings' addresses
Reading the documentation, this might rely on a modern enough Postgres with the certain features enabled, but I think they're pretty standard. Works fine with my local Postgres out of the box. We'll find out if they're enabled for our CI and staging environment soon!

Add searching of developments

---

app/models/dwelling.rb
spec/factories.rb
spec/features/creating_dwellings_spec.rb
spec/features/editing_dwellings_spec.rb

Ensure that we don't allow the creation of multiple dwellings within a development that have the same reference IDs.
Had to tweak the factories and some other tests to support this.

Validate uniquness of dwelling reference ID within development

---

app/views/developments/show.html.haml

- change 'Address' to 'Site address'
- 'Site address' always comes before  'Proposal'

development page formatting

---

app/assets/stylesheets/components/_subnavigation.scss

Important for a11y.
Before:<img width="735" alt="before" src="https://user-images.githubusercontent.com/822507/69954392-18913780-14f3-11ea-8f97-d2081d7b2063.png">
After:<img width="726" alt="after" src="https://user-images.githubusercontent.com/822507/69954395-19c26480-14f3-11ea-89f0-cae295b4515e.png">

adds gov.uk-style focus styles for subnavigation links

---

app/assets/stylesheets/components/_state-labels.scss
app/views/developments/agree_confirmation.html.haml
app/views/developments/complete_confirmation.html.haml
app/views/developments/start_confirmation.html.haml
app/views/partials/_statuses.haml

-  when a user goes to change the status of a development, they can access detailed descriptions of all the statuses in a [`<details>` element pattern from the GOV.UK design system.](https://design-system.service.gov.uk/components/details/)

status descriptions on confirmation pages

---

app/models/dwellings_statistics.rb
app/views/partials/_statistics.html.haml

We're inconsistent in saying 'unit' and 'dwelling'. We probably want to rename everything to unit, but it's much easier for now to be consistent with calling everything dwelling.

Rename 'unit' in statistics to 'dwellings'

---

yarn.lock

This includes a bump of dependencies, one of which had a vulnerability.
Original PR to update the dependency of a dependency of webpacker: https://github.com/webpack-contrib/compression-webpack-plugin/pull/139
I've tested both `bin/webpacker-dev-server` and `bin/webpack` and both compile without error.

Update @rails/webpacker to 4.2.2

---

buildspec.yml

* `INFRA_ENV` is set in CodePipeline through dalmatian

(Fix) Add RAILS_ENV to buildspec

---

app/controllers/developments_controller.rb
app/models/dwelling.rb
app/views/developments/_dwellings.html.haml
app/views/developments/completion_response_form.html.haml
db/migrate/20210127133211_add_tenure_product_to_dwellings.rb
db/schema.rb
spec/features/developer_completion_response_spec.rb

At completion, the more general "open/social/intermediate" gets more specific to a specific tenure product.
We now ask the developer to let us know what product they used.

Add tenure products to dwellings

---

config/webpacker.yml

* `resolved_paths` has been depreciated in favour of `additional_paths`
* https://github.com/rails/webpacker/commit/0adb3dc342addaa00122f9b022bf05606225c39c#diff-04c6e90faac2675aa89e2176d2eec7d8R365

(Fix) webpacker additional_paths

---

app/models/dwelling.rb

This is to more closely match real world data entered by RPs and the data structure in the Affordable Housing Monitoring tool.
"other" has been added to the list
Many new options have been added e.g. "Housing for older people", "Supported Housing", and "Rough sleepers initiative"

Add new tenures and tenure products

---

Brewfile
CHANGELOG.md
README.md
script/bootstrap
script/server
script/setup
script/test

Now that we're doing some support tasks on the Alpha codebase, I thought it'd be useful to try and make this project more in line with our usual pattern for doing things.
This PR:
- Adds scripts to rule them all to get set up and run the app locally
- Updates README for a bit more detail
- Adds a CHANGELOG & a release process

Update documentation & make project easier to support

---

Dockerfile

- Dockerfile now installs latest npm
- npm then installs LTS node
- the LTS node is to ensure that we have a version >= 12.2.0 which is needed to run certain dependencies in the project (namely normalizeurl)
- previously we were on node 10
FAO reviewer: 
- aware that installing the *latest* npm might not be super safe - do flag if wiser to install named npm version instead, and that version can then install LTS node

edits Dockerfile to install latest npm and LTS node

---

.gitignore

**NB: we need to merge https://github.com/dxw/affordable-housing-monitoring/pull/222 to "build" (run our tests) using Github Actions rather than via CircleCI which isn't working -- and for which I can't find credentials.**
This helps protects against inadvertent data breaches.

Ignore common data file formats
